# Generated by Django 3.1.4 on 2020-12-08 07:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('group_me_id', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('do_fine_periods_loop', models.BooleanField()),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishbot.groupmeuser')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('houses', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FinePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('duration', models.DurationField(default=datetime.timedelta(days=1))),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_current_fine_period', models.BooleanField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fine_periods', to='dishbot.house')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishbot.groupmeuser')),
            ],
            managers=[
                ('fine_periods', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Dishwasher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.IntegerField()),
                ('is_current_dishwasher', models.BooleanField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishwashers', to='dishbot.house')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishbot.groupmeuser')),
            ],
            managers=[
                ('dishwashers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='fineperiod',
            constraint=models.UniqueConstraint(fields=('house', 'order'), name='no two fines can have the same order per house'),
        ),
        migrations.AddConstraint(
            model_name='fineperiod',
            constraint=models.UniqueConstraint(condition=models.Q(is_current_fine_period=True), fields=('house', 'is_current_fine_period'), name='only one fine period can be current per house'),
        ),
        migrations.AddConstraint(
            model_name='dishwasher',
            constraint=models.UniqueConstraint(fields=('house', 'order'), name='no two dishwashers can have the same order per house'),
        ),
        migrations.AddConstraint(
            model_name='dishwasher',
            constraint=models.UniqueConstraint(condition=models.Q(is_current_dishwasher=True), fields=('house', 'is_current_dishwasher'), name='only one dishwasher can be current per house'),
        ),
    ]
